spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  kafka:
    topic:
      #userTopic: feed-to-alarm
      #userTopic: stream-calc-input-feed
      userTopic: stream-calc-test111
    bootstrap-servers: 192.168.188.81:9092
    producer:
      batch-size: 65536
      buffer-memory: 524288
    consumer:
      group-id: iot  #group-id是所属分组（kafka要求一个分组的成员数量不能大于设置的分区数，否则同一个分组中多出的成员永远都不会收到消息）
      enable-auto-commit: true

  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2  # 连接池中的最小空闲连接
    timeout: 20000
    # 集群环境打开下面注释，单机不需要打开
    #cluster:
    # 集群信息
    #  nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
     # 默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
      #max-redirects: 3
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iamlook.model
  type-enums-package: com.iamlook.enumeration #配置扫描枚举
  #该属性是作用在java-bean
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  config: classpath:logback-spring.xml
  path: /home/sddt/youxun/log

