spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fan?characterEncoding=utf-8&useSSL=false
    username: sddt
    password: sddt8888
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  kafka:
    topic:
      userTopic: feed-to-alarm
    bootstrap-servers: 180.97.165.53:9092
    producer:
      batch-size: 65536
      buffer-memory: 524288
    consumer:
      group-id: kafka001  #group-id是所属分组（kafka要求一个分组的成员数量不能大于设置的分区数，否则同一个分组中多出的成员永远都不会收到消息）
      auto-offset-reset: earliest  #auto-offset-reset设为earliest是获取以前就有过的消息（其实不是必要的配置）
      enable-auto-commit: true

  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2  # 连接池中的最小空闲连接
    timeout: 20000
    # 集群环境打开下面注释，单机不需要打开
    #cluster:
    # 集群信息
    #  nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
     # 默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
      #max-redirects: 3
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iamlook.model
  type-enums-package: com.iamlook.enumeration #配置扫描枚举
  #该属性是作用在java-bean
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  config: classpath:logback-spring.xml
  path: /home/sddt/youxun/log

