spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.152.37:3306/iambook?characterEncoding=utf-8&useSSL=false
    username: root
    password: Demonstrate~123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


