spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.152.37:3306/iambook?characterEncoding=utf-8&useSSL=false
    username: root
    password: Demonstrate~123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2  # 连接池中的最小空闲连接
    timeout: 0  # 连接超时时间（毫秒）




